# Data Wrangling Challenge
### Pull and manipulate the API data

The point of this exercise is to try data enrichment with data from external APIs. We are going to take data about car crashes in Monroe County, Indiana from 2003 to 2015 and try to figure out the weather during the accident and how many bars there are in the area. We will work with two different APIs during this challenge:

- Foursquare API
- World Weather Online API

We will try to find correlations between the severity of crash and weather/number of bars in the area. To indicate the severity of a crash, we will use column `Injury Type`.

## Data

The data for this exercise can be found [here](https://drive.google.com/file/d/1_KF9oIJV8cB8i3ngA4JPOLWIE_ETE6CJ/view?usp=sharing).

Just run the cells below to get your data ready. Little help from us.

In [4]:
import pandas as pd
import os
from bs4 import BeautifulSoup
import requests
import numpy as np

In [15]:
data = pd.read_csv("monroe-county-crash-data2003-to-2015.csv", encoding="unicode_escape")
# ========================
# preparing data
data.dropna(subset=['Latitude', 'Longitude'], inplace=True)
# creation of variable with lon and lat together
data['ll'] = data['Latitude'].astype(str) + ',' + data['Longitude'].astype(str)
data = data[data['ll'] != '0.0,0.0']
print(data.shape)

(49005, 13)

In [16]:
data

,Master Record Number,Year,Month,Day,Weekend?,Hour,Collision Type,Injury Type,Primary Factor,Reported_Location,Latitude,Longitude,ll
0,902363382,2015,1,5,Weekday,0.0,2-Car,No injury/unknown,OTHER (DRIVER) - EXPLAIN IN NARRATIVE,1ST & FESS,39.159207,-86.525874,"39.15920668,-86.52587356"
1,902364268,2015,1,6,Weekday,1500.0,2-Car,No injury/unknown,FOLLOWING TOO CLOSELY,2ND & COLLEGE,39.161440,-86.534848,"39.16144,-86.534848"
2,902364412,2015,1,6,Weekend,2300.0,2-Car,Non-incapacitating,DISREGARD SIGNAL/REG SIGN,BASSWOOD & BLOOMFIELD,39.149780,-86.568890,"39.14978027,-86.56889006"
3,902364551,2015,1,7,Weekend,900.0,2-Car,Non-incapacitating,FAILURE TO YIELD RIGHT OF WAY,GATES & JACOBS,39.165655,-86.575956,"39.165655,-86.57595635"
4,902364615,2015,1,7,Weekend,1100.0,2-Car,No injury/unknown,FAILURE TO YIELD RIGHT OF WAY,W 3RD,39.164848,-86.579625,"39.164848,-86.57962482"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53344,521147,2003,4,7,Weekend,2000.0,1-Car,No injury/unknown,UNSAFE SPEED,POPCORN RD & ROCKPORT,39.004275,-86.581375,"39.00427482,-86.58137523"
53345,521157,2003,5,7,Weekend,1500.0,1-Car,Non-incapacitating,UNSAFE SPEED,GUTHERIE RD & PRINCE,39.002752,-86.463856,"39.002752,-86.463856"
53346,900087672,2003,11,3,Weekday,2300.0,1-Car,No injury/unknown,ROADWAY SURFACE CONDITION,INGRAM & SR37,38.992326,-86.537252,"38.99232624,-86.53725171"
53347,919959,2003,12,7,Weekend,1700.0,1-Car,Non-incapacitating,UNSAFE SPEED,BARTLETTSVILLE & CHAPLE HILL RD,38.991520,-86.448784,"38.99152,-86.448784"
53348,900046599,2003,6,7,Weekend,800.0,1-Car,No injury/unknown,NaN,OLD & SR446,38.990848,-86.368864,"38.990848,-86.368864"

# Foursquare API

Foursquare API documentation is [here](https://developer.foursquare.com/)

1. Start a foursquare application and get your keys.
2. For each crash, create the function **get_venues** that will pull bars in the radius of 5km around the crash

#### example
`get_venues('48.146394, 17.107969')`

3. Find a relationship (if there is any) between number of bars in the area and severity of the crash.

HINTs: 
- check out python package "foursquare" (no need to send HTTP requests directly with library `requests`)
- **categoryId** for bars and nightlife needs to be found in the [foursquare API documentation](https://developer.foursquare.com/docs/api-reference/venues/search/)

In [ ]:
# loop through the indexes
#for each ll in data[ll]
# run querry
# put output in column

In [16]:
#set the keys
foursquare_id = os.environ["LUMSN0QW0GKQUKJB3CQQAV1Y3DGYXJC4U2TX5FUKMTA5IK5H"]
foursquare_secret = os.environ["OBFVZ5PZ2QFA55BOIGVMF50RO3LL4WJDUUN23ACI4VCZJ0Y4"]

In [6]:
Latitude = data['Latitude']
longitude = data['Longitude']
api_key = 'FOURSQUARE_API_KEY'

In [62]:
Bars = []
data_index = list(data.index)
for idx in data_index:
      url = 'https://api.foursquare.com/v3/places/search'
      params = {
            # "query": "bar",
            "categories": "13003,13007,13024,13016,13018,13025,13011,13009",
            "ll": data.loc[idx, "ll"],
            "radius": 5000,
            "sort":"DISTANCE"
      }
      headers = {
            "accept": "application/json",
            "Authorization": 'fsq3mpmXXTeUamPeksBb3eR6RVdXFef1JiEGX1JZDH5QoUA='
      }
      response = requests.request("GET", url, params=params, headers=headers)

      #print(response.text)
      res_json = response.json()
      try:
            result_1 = res_json['results']

      except KeyError:
            pass
      
      # print(result_1)
      Bars.append(len(result_1))
      #print(len(Bars))

In [63]:
#data['Bars'] = Bars

Bars

[10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 10,
 10,
 10,
 10,
 4,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 2,
 2,
 10,
 10,
 2,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 4,
 4,
 10,
 0,
 10,
 10,
 10,
 5,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 1,
 10,
 10,
 10,
 10,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 2,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 0,
 10,
 10,
 7,
 10,
 6,
 10,
 10,
 2,
 0,
 0,
 10,
 1,
 10,
 2,
 10,
 0,
 3,
 3,
 3,
 10,
 10,
 10,
 1,
 3,
 10,
 10,
 10,
 6,
 1,
 10,
 10,
 5,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 6,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 4,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 4,
 1,
 2,
 10,
 10,
 0,
 10,
 2,
 4,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 8,
 1,
 8,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 3,
 0,
 10,
 4,
 10,
 10,
 1,
 0,
 2,
 6,
 10,
 10,
 10,
 3,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 8,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 3,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 9,
 10,
 3,
 10,
 10,
 0,
 10,
 10,
 2,
 9,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 0,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 8,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 6,
 10,
 10,
 10,
 5,
 10,
 10,
 0,
 10,
 10,
 7,
 10,
 10,
 10,
 6,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 0,
 5,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 3,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 3,
 0,
 10,
 4,
 8,
 10,
 2,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 9,
 10,
 10,
 10,
 10,
 10,
 2,
 4,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 5,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 2,
 10,
 1,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 3,
 10,
 6,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 3,
 10,
 10,
 3,
 10,
 10,
 10,
 8,
 8,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 5,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 7,
 10,
 10,
 10,
 0,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 0,
 3,
 0,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 3,
 10,
 0,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 8,
 10,
 0,
 5,
 10,
 10,
 10,
 1,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 5,
 1,
 10,
 10,
 1,
 10,
 10,
 0,
 10,
 10,
 4,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 5,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 2,
 9,
 10,
 0,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 3,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 4,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 10,
 10,
 4,
 2,
 0,
 1,
 10,
 8,
 10,
 3,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 0,
 10,
 0,
 10,
 10,
 7,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 0,
 0,
 0,
 10,
 0,
 10,
 10,
 10,
 4,
 10,
 10,
 10,
 10,
 10,
 2,
 2,
 10,
 0,
 3,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 9,
 2,
 10,
 10,
 1,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 2,
 0,
 10,
 10,
 0,
 7,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 1,
 10,
 10,
 10,
 3,
 10,
 10,
 10,
 10,
 2,
 10,
 10,
 10,
 0,
 10,
 10,
 10,
 6,
 1,
 10,
 10,
 10,
 10,
 4,
 10,
 10,
 10,
 10,
 10,
 0,
 1,
 10,
 9,
 10,
 10,
 2,
 10,
 10,
 10,
 10,
 10,
 ...]

In [67]:
data['Bars'] = Bars

In [68]:
data.head(10)

,Master Record Number,Year,Month,Day,Weekend?,Hour,Collision Type,Injury Type,Primary Factor,Reported_Location,Latitude,Longitude,ll,from Bars,Bars
0,902363382,2015,1,5,Weekday,0.0,2-Car,No injury/unknown,OTHER (DRIVER) - EXPLAIN IN NARRATIVE,1ST & FESS,39.159207,-86.525874,"39.15920668,-86.52587356",10,10
1,902364268,2015,1,6,Weekday,1500.0,2-Car,No injury/unknown,FOLLOWING TOO CLOSELY,2ND & COLLEGE,39.161440,-86.534848,"39.16144,-86.534848",10,10
2,902364412,2015,1,6,Weekend,2300.0,2-Car,Non-incapacitating,DISREGARD SIGNAL/REG SIGN,BASSWOOD & BLOOMFIELD,39.149780,-86.568890,"39.14978027,-86.56889006",10,10
3,902364551,2015,1,7,Weekend,900.0,2-Car,Non-incapacitating,FAILURE TO YIELD RIGHT OF WAY,GATES & JACOBS,39.165655,-86.575956,"39.165655,-86.57595635",10,10
4,902364615,2015,1,7,Weekend,1100.0,2-Car,No injury/unknown,FAILURE TO YIELD RIGHT OF WAY,W 3RD,39.164848,-86.579625,"39.164848,-86.57962482",10,10
5,902364664,2015,1,6,Weekday,1800.0,2-Car,No injury/unknown,FAILURE TO YIELD RIGHT OF WAY,BURKS & WALNUT,39.126670,-86.531370,"39.12666969,-86.53136998",10,10
6,902364682,2015,1,6,Weekday,1200.0,2-Car,No injury/unknown,DRIVER DISTRACTED - EXPLAIN IN NARRATIVE,SOUTH CURRY PIKE LOT 71,39.150825,-86.584899,"39.150825,-86.584899",10,10
7,902364683,2015,1,6,Weekday,1400.0,1-Car,Incapacitating,ENGINE FAILURE OR DEFECTIVE,NORTH LOUDEN RD,39.199272,-86.637024,"39.19927216,-86.63702393",2,2
8,902364714,2015,1,7,Weekend,1400.0,2-Car,No injury/unknown,FOLLOWING TOO CLOSELY,LIBERTY & W 3RD,39.164610,-86.579130,"39.16461021,-86.57913007",10,10
9,902364756,2015,1,7,Weekend,1600.0,1-Car,No injury/unknown,RAN OFF ROAD RIGHT,PATTERSON & W 3RD,39.163440,-86.551280,"39.16344009,-86.55128002",10,10

# World Weather Online API

World Weather Online API is [here](https://www.worldweatheronline.com/developer/api/historical-weather-api.aspx)

1. Sign up for FREE api key if you haven't done that before (it's free for **30 days**).
2. For each crush, get the weather for the location and date.
3. Find a relationship between the weather and severity of the crash.

Hints:

* pull weather only for smaller sample of crashes (250 or so) due to API limits
* for sending HTTP requests check out "requests" library [here](http://docs.python-requests.org/en/master/)

In [193]:
import requests
import time
api_key = os.environ["<>"]

In [9]:
locations = []
index = 0
while index < 10:
    i = index
    if index == 11:
        break
    index += 1

for i in np.arange(0, 4600):
    locations.append(data['ll'][i])

locations

KeyError: 58

In [46]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
    },
    index=[0, 1, 2, 3],
)

In [39]:
df1

    A
0  A0
1  A1
2  A2
3  A3

In [47]:
df2 = [10, 15, 0, 20]

In [48]:
df1['from df2'] = df2

In [49]:
df1

    A  from df2
0  A0        10
1  A1        15
2  A2         0
3  A3        20